### PR TITLE
fix grammar/spelling in readme for RoboCar image localization

### PR DESCRIPTION
**Pull request by ckirksey3**

### CODE REVIEW

**Comment by NikolasEnt** [comment]
Thank you very much for the proofreading!

**Comment by ckirksey3** [comment]
@NikolasEnt sure thing! Congrats on getting your work in the project. I'm trying to start contributing in small ways. Is @mjshiggins the one who needs to merge the PR?

**Comment by kfet** [comment]
ог
още малк

**Comment by NikolasEnt** [comment]
@ckirksey3 Yes, he is.

**Pull request merged**
